// ui/src/components/AddSourceModal.tsx
import React, { useRef } from "react";
import { X } from "lucide-react";

interface AddSourceModalProps {
  show: boolean;
  onClose: () => void;
  onAddReflection: (host: string, port: number) => void;
  onAddDescriptor: (file: File) => void;
}

export const AddSourceModal: React.FC<AddSourceModalProps> = ({
  show,
  onClose,
  onAddReflection,
  onAddDescriptor,
}) => {
  const hostRef = useRef<HTMLInputElement>(null);
  const portRef = useRef<HTMLInputElement>(null);

  if (!show) return null;

  const handleReflection = () => {
    const host = hostRef.current?.value || "127.0.0.1";
    const port = parseInt(portRef.current?.value || "10000", 10);
    onAddReflection(host, port);
    onClose();
  };

  const handleDescriptor = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      onAddDescriptor(e.target.files[0]);
      onClose();
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center">
      <div className="bg-white rounded shadow-lg w-[500px] overflow-hidden">
        <div className="flex justify-between items-center p-4 border-b">
          <h3 className="text-lg font-medium text-gray-900">Add Source</h3>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700"
          >
            <X size={20} />
          </button>
        </div>

        <div className="p-4 space-y-6">
          {/* Reflection Section */}
          <div>
            <h4 className="font-medium text-purple-600 mb-2">
              Server Reflection
            </h4>
            <div className="flex gap-2">
              <input
                ref={hostRef}
                defaultValue="127.0.0.1"
                placeholder="Host"
                className="border rounded p-2 flex-grow outline-none focus:border-purple-600"
              />
              <input
                ref={portRef}
                placeholder="Port"
                type="number"
                className="border rounded p-2 w-24 outline-none focus:border-purple-600"
              />
              <button
                onClick={handleReflection}
                className="bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700 uppercase text-sm font-medium"
              >
                Add
              </button>
            </div>
          </div>

          <div className="border-t"></div>

          <div>
            <h4 className="font-medium text-purple-600 mb-2">Descriptor Set</h4>
            <div className="flex items-center">
              <input
                type="file"
                className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-purple-50 file:text-purple-700 hover:file:bg-purple-100"
                onChange={handleDescriptor}
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// frontend/src/components/AddSourceModal.vue
<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{
  show: boolean;
}>();

const emit = defineEmits<{
  (e: "close"): void;
  (e: "add-reflection", host: string, port: number): void;
  (e: "add-descriptor", file: File): void;
}>();

const mode = ref<"reflection" | "file">("reflection");
const host = ref("127.0.0.1");
const port = ref(10000);
const file = ref<File | null>(null);

const onFileChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  if (target.files && target.files.length > 0) {
    file.value = target.files[0];
  }
};

const submit = () => {
  if (mode.value === "reflection") {
    emit("add-reflection", host.value, port.value);
  } else {
    if (file.value) {
      emit("add-descriptor", file.value);
    }
  }
  close();
};

const close = () => {
  emit("close");
};
</script>

<template>
  <div v-if="show" class="modal-overlay" @click.self="close">
    <div class="modal">
      <div class="modal-header">
        <h3>Add Source</h3>
        <button class="close-btn" @click="close">×</button>
      </div>
      <div class="modal-body">
        <div class="tabs">
          <button
            :class="{ active: mode === 'reflection' }"
            @click="mode = 'reflection'"
          >
            Reflection
          </button>
          <button :class="{ active: mode === 'file' }" @click="mode = 'file'">
            Descriptor Set
          </button>
        </div>

        <div v-if="mode === 'reflection'" class="form-group">
          <label>Host</label>
          <input v-model="host" type="text" placeholder="localhost" />
          <label>Port</label>
          <input v-model="port" type="number" placeholder="8080" />
        </div>

        <div v-if="mode === 'file'" class="form-group">
          <label>File Descriptor Set (.pb, .bin, .desc)</label>
          <input type="file" @change="onFileChange" accept=".pb,.bin,.desc" />
        </div>
      </div>
      <div class="modal-footer">
        <button class="cancel-btn" @click="close">Cancel</button>
        <button class="add-btn" @click="submit">Add</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal {
  background: white;
  border-radius: 8px;
  width: 400px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  display: flex;
  flex-direction: column;
}

.modal-header {
  padding: 16px;
  border-bottom: 1px solid #eee;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
}

.close-btn {
  background: none;
  border: none;
  font-size: 24px;
  cursor: pointer;
  padding: 0;
  line-height: 1;
}

.modal-body {
  padding: 16px;
}

.tabs {
  display: flex;
  margin-bottom: 16px;
  border-bottom: 1px solid #eee;
}

.tabs button {
  padding: 8px 16px;
  border: none;
  background: none;
  cursor: pointer;
  font-weight: 500;
  color: #666;
  border-bottom: 2px solid transparent;
}

.tabs button.active {
  color: #6200ee;
  border-bottom-color: #6200ee;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

input {
  padding: 8px;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.modal-footer {
  padding: 16px;
  border-top: 1px solid #eee;
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}

button.add-btn {
  background: #6200ee;
  color: white;
  padding: 8px 16px;
  border-radius: 4px;
  border: none;
  cursor: pointer;
}

button.cancel-btn {
  background: white;
  color: #666;
  padding: 8px 16px;
  border-radius: 4px;
  border: 1px solid #ddd;
  cursor: pointer;
}
</style>
