// ui/src/components/TreeView.tsx
import React, { useState } from "react";
import { ItemWithId } from "@/lib/store";
import {
  ChevronRight,
  ChevronDown,
  Folder,
  FolderOpen,
  FileText,
  FilePlus,
  FolderPlus,
  Check,
  X,
  Trash2,
} from "lucide-react";

interface TreeViewProps {
  item: ItemWithId;
  onAddItem: (parent: ItemWithId, item: ItemWithId) => void;
  onRemoveItem: (parent: ItemWithId, index: number) => void;
}

export const TreeView: React.FC<TreeViewProps> = ({
  item,
  onAddItem,
  onRemoveItem,
}) => {
  const [isOpen, setIsOpen] = useState(true);
  const [newType, setNewType] = useState<"grpc" | "folder" | null>(null);
  const [newName, setNewName] = useState("");

  const toggleOpen = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (item.type === "folder") {
      setIsOpen(!isOpen);
    }
  };

  const startAddFile = (e: React.MouseEvent) => {
    e.stopPropagation();
    setNewType("grpc");
    setNewName("");
    setIsOpen(true);
  };

  const startAddFolder = (e: React.MouseEvent) => {
    e.stopPropagation();
    setNewType("folder");
    setNewName("");
    setIsOpen(true);
  };

  const cancelAdd = () => {
    setNewType(null);
    setNewName("");
  };

  const confirmAdd = () => {
    if (newName.trim() && newType) {
      onAddItem(item, {
        name: newName,
        type: newType,
        id: crypto.randomUUID(),
        children: [],
      });
    }
    cancelAdd();
  };

  const handleRemoveChild = (child: ItemWithId, index: number) => {
    onRemoveItem(item, index);
  };

  return (
    <div className="font-roboto text-sm select-none text-gray-800">
      <div className="flex items-center px-2 h-8 cursor-pointer hover:bg-black/5 group rounded mx-1">
        <span
          className="flex items-center justifying-center w-6 h-6 mr-1 rounded-full hover:bg-black/10"
          onClick={toggleOpen}
          style={{ visibility: item.type === "folder" ? "visible" : "hidden" }}
        >
          {isOpen ? (
            <ChevronDown size={18} className="text-gray-500" />
          ) : (
            <ChevronRight size={18} className="text-gray-500" />
          )}
        </span>

        <span className="mr-2 text-gray-600" onClick={toggleOpen}>
          {item.type === "folder" ? (
            isOpen ? (
              <FolderOpen size={18} />
            ) : (
              <Folder size={18} />
            )
          ) : (
            <FileText size={18} />
          )}
        </span>

        <span
          className="flex-grow whitespace-nowrap overflow-hidden text-ellipsis font-normal text-gray-900"
          onClick={toggleOpen}
        >
          {item.name || "Root"}
        </span>

        <div className="flex items-center opacity-0 group-hover:opacity-100 transition-opacity">
          {item.type === "folder" && (
            <>
              <button
                onClick={startAddFile}
                title="Add Request"
                className="p-1 rounded-full hover:bg-black/10 text-gray-600"
              >
                <FilePlus size={16} />
              </button>
              <button
                onClick={startAddFolder}
                title="Add Group"
                className="p-1 rounded-full hover:bg-black/10 text-gray-600"
              >
                <FolderPlus size={16} />
              </button>
            </>
          )}
        </div>
      </div>

      {newType !== null && (
        <div className="flex items-center pl-8 pr-2 h-8">
          <input
            value={newName}
            onChange={(e) => setNewName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") confirmAdd();
              if (e.key === "Escape") cancelAdd();
            }}
            placeholder="Name..."
            className="flex-grow border-none border-b-2 border-purple-600 bg-gray-100 text-sm px-2 py-1 outline-none rounded-t"
            autoFocus
          />
          <button
            onClick={confirmAdd}
            className="p-1 ml-1 rounded-full hover:bg-black/10 text-green-600"
          >
            <Check size={18} />
          </button>
          <button
            onClick={cancelAdd}
            className="p-1 ml-1 rounded-full hover:bg-black/10 text-red-600"
          >
            <X size={18} />
          </button>
        </div>
      )}

      {isOpen && item.children && item.children.length > 0 && (
        <div className="ml-7">
          {item.children.map((child, index) => (
            <div key={child.id || index} className="relative group/child">
              <TreeView
                item={child}
                onAddItem={onAddItem}
                onRemoveItem={onRemoveItem}
              />
              <button
                className="absolute top-1 right-2 opacity-0 group-hover/child:opacity-100 transition-opacity p-1 rounded-full hover:bg-black/10 text-gray-600 z-10"
                onClick={(e) => {
                  e.stopPropagation();
                  handleRemoveChild(child, index);
                }}
                title="Delete"
              >
                <Trash2 size={16} />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// frontend/src/components/TreeView.vue
<script lang="ts" setup>
import { type Item } from "@/stores/workspace";
import { ref } from "vue";

const props = defineProps<{
  item: Item;
}>();

const emit = defineEmits<{
  addItem: [Item, Item];
  removeItem: [Item, number];
  renameItem: [Item, string];
}>();

const newItemName = ref("");
const isAddingFile = ref(false);
const isAddingFolder = ref(false);
const isOpen = ref(true); // Default open

const startAddFile = () => {
  isAddingFile.value = true;
  isAddingFolder.value = false;
  newItemName.value = "";
};

const startAddFolder = () => {
  isAddingFolder.value = true;
  isAddingFile.value = false;
  newItemName.value = "";
};

const cancelAdd = () => {
  isAddingFile.value = false;
  isAddingFolder.value = false;
  newItemName.value = "";
};

const confirmAdd = () => {
  if (newItemName.value.trim()) {
    const type = isAddingFile.value ? "grpc" : "folder";
    emit("addItem", props.item, { name: newItemName.value, type: type });
    isOpen.value = true; // Ensure open when adding
  }
  cancelAdd();
};

const toggleOpen = () => {
  if (props.item.type === "folder") {
    isOpen.value = !isOpen.value;
  }
};

const handleRemoveChild = (child: Item, index: number) => {
  emit("removeItem", props.item, index);
};
</script>

<template>
  <div class="tree-node">
    <div class="node-row" :class="{ 'is-selected': false }">
      <!-- Icon / Toggler -->
      <span
        class="icon-wrapper"
        @click="toggleOpen"
        :style="{ visibility: item.type === 'folder' ? 'visible' : 'hidden' }"
      >
        <span class="material-icons toggle-icon">
          {{ isOpen ? "expand_more" : "chevron_right" }}
        </span>
      </span>

      <!-- Item Type Icon -->
      <span class="material-icons type-icon" @click="toggleOpen">
        {{
          item.type === "folder"
            ? isOpen
              ? "folder_open"
              : "folder"
            : "description"
        }}
      </span>

      <!-- Name -->
      <span class="name" @click="toggleOpen">{{ item.name || "Root" }}</span>

      <!-- Actions -->
      <div class="actions">
        <!-- Folder Actions -->
        <template v-if="item.type === 'folder'">
          <button
            @click.stop="startAddFile"
            title="Add Request"
            class="icon-btn"
          >
            <span class="material-icons">note_add</span>
          </button>
          <button
            @click.stop="startAddFolder"
            title="Add Group"
            class="icon-btn"
          >
            <span class="material-icons">create_new_folder</span>
          </button>
        </template>
        <!-- Delete is handled by the parent list for children -->
      </div>
    </div>

    <!-- Add Form -->
    <div v-if="isAddingFile || isAddingFolder" class="add-form">
      <input
        v-model="newItemName"
        @keyup.enter="confirmAdd"
        @keyup.esc="cancelAdd"
        placeholder="Name..."
        class="input-name"
        autoFocus
      />
      <button @click="confirmAdd" class="icon-btn action-confirm">
        <span class="material-icons">check</span>
      </button>
      <button @click="cancelAdd" class="icon-btn action-cancel">
        <span class="material-icons">close</span>
      </button>
    </div>

    <!-- Children -->
    <div
      v-if="isOpen && item.children && item.children.length"
      class="children-container"
    >
      <div
        v-for="(child, index) in item.children"
        :key="index"
        class="child-row"
      >
        <div class="child-content">
          <TreeView
            :item="child"
            @add-item="(p, i) => emit('addItem', p, i)"
            @remove-item="(p, idx) => emit('removeItem', p, idx)"
          ></TreeView>
        </div>
        <!-- Delete button for this child -->
        <button
          class="icon-btn delete-btn"
          @click="handleRemoveChild(child, index)"
          title="Delete"
        >
          <span class="material-icons">delete</span>
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.tree-node {
  font-family: "Roboto", sans-serif;
  font-size: 14px;
  user-select: none;
  color: #333;
}

.node-row {
  display: flex;
  align-items: center;
  padding: 0 8px;
  height: 32px; /* Dense list item height */
  cursor: pointer;
  border-radius: 4px;
  margin: 1px 4px;
}

.node-row:hover {
  background-color: rgba(0, 0, 0, 0.04);
}

.icon-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  margin-right: 4px;
  border-radius: 50%;
}

.icon-wrapper:hover {
  background-color: rgba(0, 0, 0, 0.08);
}

.material-icons {
  font-size: 20px;
  color: #757575;
}

.toggle-icon {
  font-size: 20px;
}

.type-icon {
  margin-right: 8px;
  color: #5f6368; /* Google Grey 700 */
}

/* Specific colors */
.type-icon:contains("folder") {
  /* CSS :contains is not valid, need conditional styling or just rely on class.
       But material folder icons usually grey or specific color.
    */
  color: #5f6368;
}

.name {
  flex-grow: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  font-weight: 400;
  color: #202124;
}

.actions {
  display: flex;
  align-items: center;
  opacity: 0;
  transition: opacity 0.2s;
}

.node-row:hover .actions {
  opacity: 1;
}

/* Icon Buttons */
.icon-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #5f6368;
  margin-left: 2px;
}

.icon-btn:hover {
  background-color: rgba(0, 0, 0, 0.08); /* Ink ripple effect equivalent */
  color: #202124;
}

.icon-btn .material-icons {
  font-size: 18px;
}

/* Children alignment */
.children-container {
  margin-left: 28px; /* Indent under the type icon */
  /* Remove border line for Material Design usually */
}

.child-row {
  display: flex;
  align-items: flex-start;
  position: relative; /* For delete btn positioning context if needed */
}

.child-content {
  flex-grow: 1;
  min-width: 0;
}

.delete-btn {
  opacity: 0;
  transition: opacity 0.2s;
  margin-top: 0; /* Align with row */
  /* Position it absolutely or just flex? Flex is fine. */
  height: 32px; /* Match row height */
  width: 32px;
}

.child-row:hover > .delete-btn {
  opacity: 1;
}

/* Add Form */
.add-form {
  display: flex;
  align-items: center;
  padding: 0 8px 0 32px;
  height: 32px;
}

.input-name {
  flex-grow: 1;
  border: none;
  border-bottom: 2px solid #6200ee;
  background-color: #f5f5f5;
  font-size: 14px;
  padding: 4px 8px;
  outline: none;
  border-radius: 4px 4px 0 0;
}

.action-confirm .material-icons {
  color: #4caf50;
}
.action-cancel .material-icons {
  color: #f44336;
}
</style>
